### ISSUE TITLE
Error: Must use import to load ES Module. <all: true>

### ISSUE THREAD

**Issue by IgorNovozhilov** [istanbuljs/esm-loader-hook#1]
`Error: Must use import to load ES Module: ...`

If I use  configuration: `all: true`, I get this exception. Without it, everything is fine.

### example
https://github.com/nodutilus/nyc-config/tree/dev/istanbuljs/esm-loader-hook
> comand: `node bin`

##### config `nyc.config.cjs`:
```js
module.exports = {
  all: true
}

```

##### output
```
(node:6077) ExperimentalWarning: The ESM module loader is experimental.
> npx cross-env 'NODE_OPTIONS=--experimental-loader @istanbuljs/esm-loader-hook' nyc node test
(node:6100) ExperimentalWarning: The ESM module loader is experimental.
(node:6100) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
Must use import to load ES Module: /home/igor/development/nodutilus/nyc-config/test/extpkg/class-properties.js
child_process.js:611
    err = new Error(msg);
          ^

Error: Command failed: npx cross-env 'NODE_OPTIONS=--experimental-loader @istanbuljs/esm-loader-hook' nyc node test
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at execCommand (file:///home/igor/development/nodutilus/nyc-config/node_modules/@nodutilus/ci-cd/lib/child.js:10:3)
    at file:///home/igor/development/nodutilus/nyc-config/bin.js:5:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6088,
  stdout: null,
  stderr: null
}
```

**Comment by coreyfarrell** [comment]
This is a known limitation which needs to be documented.  Technically this is a bug in nyc but I'm not aware of a solution.  Part of the problem is that node.js does not (yet?) have a way to query which loader is to be used for a file.  nyc could be smarter about how it handles `.mjs` files but `.js` files are more difficult.

**Comment by IgorNovozhilov** [comment]
And check the type of package is not enough for this? [<package.json "type" field>](https://nodejs.org/api/esm.html#esm_package_json_type_field)
For `.js ' file up a tree to the nearest package and check its type?

**Comment by coreyfarrell** [comment]
That is what node.js does internally, the hope is for node.js to expose a function to determine the type of /path/to/file.js.  node.js has the necessary package.json fields cached so the goal is for nyc to avoid re-implementing this.

Even once that format check is accomplished we have additional concerns for nyc.  For example what happens if a composite ESM loader hook is being used - for example if someone is combining a coffee script transpiler with this istanbul loader hook.  We cannot simply transpile the coffee script source.

For now the experimental nature of this whole support is blocking changes to nyc itself.  Enabling nyc to support `all: true` on ES modules would put me in a bad situation with nyc support.  Sorry I know this is not the answer you want but the reality of using experimental stuff is that not everything works yet.

**Comment by IgorNovozhilov** [comment]
> For now the experimental nature of this whole support is blocking changes to nyc itself.

Is it time?
https://nodejs.org/en/blog/release/v14.0.0/

it may be worth making an additional option for nyc-config? `esm: true`, When it is enabled, all files will be considered as modules.

**Comment by coreyfarrell** [comment]
The issue is [Experimental Loaders](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_experimental_loaders).  Loader hooks are still being actively worked on and may potentially see some breaking changes.

Please understand I'm eager to get this feature fully functional but it's not possible yet.  I cannot have nyc depending on unstable parts of node.js.

**Comment by coreyfarrell** [comment]
nyc 15.1.0 works-around this issue, `.mjs` files and `.js` files under a directory where `package.json#type=module` applies.

Note that this `all: true` coverage is collected for ES modules from outside the module loader system, technically `all: true` should apply node.js loader hooks to process the input files but this is not currently possible.  This could pose problems for example if you were testing cofee-script files where you use a composite ES module loader that combines a coffee-script transformation with `@istanbuljs/esm-loader-hook`.
